export const SCHEMA_VERSION=2;
const KEY='gpa-pro:workspace',BACKUP_KEY='gpa-pro:workspace:backup';
export const defaultState=()=>({version:SCHEMA_VERSION,profile:{name:'',graduationYear:''},settings:{creditMode:true,excludeFreshman:false,coreOnly:false,weightedCap:5},courses:[],applications:[],scholarships:[],activities:[],tests:[],scenarios:[],updatedAt:new Date().toISOString()});
const text=(v,max=120)=>String(v??'').trim().slice(0,max),id=v=>text(v,80)||crypto.randomUUID();
function validCourse(v){if(!v||typeof v!=='object')return null;const credits=Number(v.credits);if(!text(v.name)||!Number.isFinite(credits)||credits<0||credits>10)return null;return{id:id(v.id),name:text(v.name),grade:text(v.grade,3),level:text(v.level,20)||'Regular',credits,year:text(v.year,20)||'Freshman',term:text(v.term,20)||'Semester 1',subject:text(v.subject,30)||'Other',planned:Boolean(v.planned),passFail:Boolean(v.passFail),replaced:Boolean(v.replaced),createdAt:text(v.createdAt,40)||new Date().toISOString()};}
const validItem=(v,fields)=>{if(!v||typeof v!=='object')return null;const item={id:id(v.id)};for(const [f,max] of fields)item[f]=text(v[f],max);return item;};
export function validateState(raw){const b=defaultState();if(!raw||typeof raw!=='object')return b;return{...b,profile:{name:text(raw.profile?.name,80),graduationYear:text(raw.profile?.graduationYear,4)},settings:{...b.settings,...raw.settings,creditMode:raw.settings?.creditMode!==false,excludeFreshman:Boolean(raw.settings?.excludeFreshman),coreOnly:Boolean(raw.settings?.coreOnly),weightedCap:Math.min(6,Math.max(4,Number(raw.settings?.weightedCap)||5))},courses:Array.isArray(raw.courses)?raw.courses.map(validCourse).filter(Boolean):[],applications:Array.isArray(raw.applications)?raw.applications.map(v=>validItem(v,[['college',120],['status',30],['deadline',20],['notes',500]])).filter(Boolean):[],scholarships:Array.isArray(raw.scholarships)?raw.scholarships.map(v=>validItem(v,[['name',120],['amount',30],['deadline',20],['status',30]])).filter(Boolean):[],activities:Array.isArray(raw.activities)?raw.activities.map(v=>validItem(v,[['name',120],['role',80],['years',30],['details',500]])).filter(Boolean):[],tests:Array.isArray(raw.tests)?raw.tests.map(v=>validItem(v,[['type',30],['score',30],['date',20]])).filter(Boolean):[],scenarios:Array.isArray(raw.scenarios)?raw.scenarios.slice(0,20):[],version:SCHEMA_VERSION};}
function legacyState(){
  const read=name=>{try{return JSON.parse(localStorage.getItem(`gpa-pro:${name}`)||'[]');}catch{return[];}};
  const courses=read('courses');
  if(!courses.length)return null;
  return{...defaultState(),courses,scholarships:read('scholarships'),applications:read('college-apps'),tests:read('test-scores'),activities:read('activities')};
}
export function loadState(){try{const current=localStorage.getItem(KEY);const migrated=current?JSON.parse(current):legacyState();return{state:validateState(migrated),warning:migrated&&!current?'Your data was upgraded to GPA Pro 2.0. Download a new backup when convenient.':''};}catch{try{return{state:validateState(JSON.parse(localStorage.getItem(BACKUP_KEY)||'null')),warning:'Your latest data was damaged, so GPA Pro restored its automatic backup.'};}catch{return{state:defaultState(),warning:'Saved data could not be read. A fresh workspace was opened.'};}}}
export function saveState(state){const validated=validateState({...state,updatedAt:new Date().toISOString()});try{const previous=localStorage.getItem(KEY);if(previous)localStorage.setItem(BACKUP_KEY,previous);localStorage.setItem(KEY,JSON.stringify(validated));return{state:validated,error:''};}catch{return{state:validated,error:'This browser could not save your changes. Download a backup before leaving.'};}}
export function importBackup(value){const parsed=JSON.parse(value);if(!parsed||typeof parsed!=='object')throw new Error('The selected file is not a GPA Pro backup.');return validateState(parsed);}
export const serializeBackup=state=>JSON.stringify(validateState(state),null,2);
